<?php
  ///////////////////
  // SAMPLE TEST CODE.
  ///////////////////
  // Generate a key; at this stage the key hasn't been configured completely.
  $new_key_entity = \Drupal::entityTypeManager()->getStorage('key')->create(array(
    "id" => "new_key2",
    "label" => "New Key",
  ));
  $new_key_entity->save();

  // Retrieve the edit form for the newly generated key.
  $form = \Drupal::entityTypeManager()->getFormObject('key', 'edit')->setEntity($new_key_entity);

  // Changing the description, as an example.
  $form_state = new \Drupal\Core\Form\FormState();
  $state = array(
    "values" => array("description" => "New Key", "op" => "Save"),
  );
  $form_state->setFormState($state);

  // Modify the key to required specifications via its edit form.
  \Drupal::formBuilder()->submitForm($form, $form_state);
